version: '3'

services:
  blog-server:
    build: ./build
    image: laravel-blog
    depends_on:
      - mysql
    volumes:
      - ./src:/application:cached

  mysql:
    image: mysql:5.7
    user: "1000:50"
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=laravel
    volumes:
      - ./src/storage/tmp/db:/var/lib/mysql:cached

  nginx:
    image: nginx
    ports:
      - "8000:8000"
    volumes:
      - ./build/nginx.conf:/etc/nginx/conf.d/default.conf:cached
      - ./src:/application:cached
    depends_on:
      - blog-server
